config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users #必要なルーティングが全て作成される。
  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  #レシピがユーザー一人にからなず属する
  attachment :image

  with_options presence: true do
    #with_optionsは複数指定したい場合に使用できる。
    #presence: trueは空の投稿ができないように制約をかけている。
    validates :title
    validates :body
    validates :image
    #空にしたくないカラムをvalidateの後ろに記述する。
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image # ここを追加（_idは含めない）

  has_many :recipes, dependent: :destroy
  #一人のユーザーはたくさんのレシピを持っているという意味
  #dependent: :destroyはユーザーが削除されたら紐付いているレシピも一緒に削除される

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  #userのページにアクセスする前にここの記述が動き、private以下に書いている記述が動く


  private
  #この中で定義したメソッドはコントローラーの中でしか使えない

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    #sign_upの時にusernameを許可するという意味
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  #:authenticate_user!はdeviseを導入するとルカえるヘルパー
  #:authenticate_user!はログインしていない人は下記の全てのアクションにアクセスできなくなる。
  #expect: [:index]を書くとindexアクションだけはアクセスできるようになる。

  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    #user_idはログインしている人
    #current_user.idは投稿するのはログインしている人
    #user_idのカラムにcurrent_user.id誰が投稿しているのかが保持される
    if @recipe.save
      #もしもセーブされたらしたの画面へいく
      redirect_to recipe_path(@recipe), notice: '投稿に成功しました。'
    else#バリデーションにかかってしまったらしたの画面にいく
      render :new
      #renderはアクションを返さずにそのビューを返すというもの
    end
    #バリデーションをかけるところはcreateアクション
  end

  def edit
    @recipe = Recipe.find(params[:id])
    if @recipe.user != current_user
      #recipeに紐付いているuserとログインユーザーが一致しなければ
      redirect_to recipes_path, alert: '不正なアクセスです。'
      #何も言わないままの遷移はアレなのでメッセージを表示させる
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      redirect_to recipe_path(@recipe),notice: '更新に成功しました。'
    else
      render :edit
    end
    #バリデーションをかけるところはupdateアクション
  end

  def destroy
    recipe = Recipe.find(params[:id])
    #削除したいレシピをRecipeモデルからひとつ持ってきてrecipeに格納する
    recipe.destroy
    #取り出してきたレシピを削除する
    redirect_to recipes_path
    #削除したら一覧に戻る
  end
  private

  def recipe_params
    params.require(:recipe).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  #:authenticate_user!はdeviseを導入するとルカえるヘルパー
  #:authenticate_user!はログインしていない人は下記の全てのアクションにアクセスできなくなる。
  #expect: [:index]を書くとindexアクションだけはアクセスできるようになる。

  def index
    @users = User.all
    #ユーザーはくさんいるので複数形にする
  end

  def show
    @user = User.find(params[:id])
    #一人のユーザーの情報を取ってきて@userに渡す
    #(params[:id])はURLから取ってきている
    #UserモデルのDBに登録してあるIDを取ってきている
  end

  def edit
    @user = User.find(params[:id])
    if @user !=current_user
      redirect_to users_path, alert: '不正なアクセスです。'
    end
  end

  def update
    @user = User.find(params[:id])
    #どのユーザーを更新するのか見つけてきて
    if @user.update(user_params)
      #@userを更新する。どのカラムを更新するのか
      #ここのuser_paramsはprivate以下の定義から取ってきている
      redirect_to user_path(@user), notice: '更新に成功しました。'
      #ユーザーの詳細画面に返る
    else
      render :edit
    end
  end

  private
  #ここはユーザーコントローラーの中でしか使えない
  def user_params
    params.require(:user).permit( :username, :email, :profile, :profile_image)
    #requireの後ろはモデル名
    #permitの後ろは更新するカラム
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">recipegram</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipegram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <%end%>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

  <nav class="navbar is-warning">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-4" style="font-family: cursive;">recipegram</h1>
      <% end %>
      <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", recipes_path, class: "button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "新規投稿", new_recipe_path, class: "button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "レシピグラマー一覧", users_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", recipes_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "レシピグラマー一覧", users_path, class: "navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ編集
      </h1>
    </div>
  </div>
</section>

<% if @recipe.errors.any? %>
<%#@recipeにエラーの内容が含まれているかどうかを判定する%>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <%#pluralizeメソッドは単語の複数形や単数系を判定してくれる。%>
    <%#"error"は一つの時は単数系で二つ以上の場合は複数形に変える%>
    <%#使い方はpluralizeの後に@recipe.errors.countエラーの数をカウントしてそれに応じて"error"を変える%>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '更新', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @recipes.each do |recipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                <%#レシピの詳細画面にいくリンクでどの詳細画面にいくかは(recipe)である%>
                  <%= attachment_image_tag recipe, :image %>
                  <%#@recipeの中にある画像を表示させたいので上記の書き方%>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= link_to user_path(recipe.user.id) do %>
                    <%#ユーザーの詳細画面にリンクでどのユーザーの詳細画面にいくかは(recipe)である%>
                      <%= attachment_image_tag recipe.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                      <%#recipe.userはrecipeに紐付いているuserという意味でfallback:はデフォルトでイメージ画像がない場合は後ろのイメージを表示させるという意味%>
                    <% end %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to recipe.user.username, user_path(recipe.user.id) %></div>
                  <%#recipeに紐付いているユーザーを取ってきたいので%>
                  <%#recipe.userはrecipeに紐付いているuserを取ってくる、その後ろにusernameとあるのは名前を表示させる%>
                </div>
              </div>

              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                <%#recipeの更新日時を取ってくる%>
                <%#.strftime("%Y-%m-%d %H:%M")は日本時間に変更するための記述%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規レシピ作成
      </h1>
    </div>
  </div>
</section>

<% if @recipe.errors.any? %>
<%#@recipeにエラーの内容が含まれているかどうかを判定する%>
  <div class="notification is-danger">
    <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <%#pluralizeメソッドは単語の複数形や単数系を判定してくれる。%>
    <%#"error"は一つの時は単数系で二つ以上の場合は複数形に変える%>
    <%#使い方はpluralizeの後に@recipe.errors.countエラーの数をカウントしてそれに応じて"error"を変える%>
    <ul>
      <% @recipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @recipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @recipe, :image %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @recipe.title %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>レシピ</th>
                </tr>
                <tr>
                  <td><%= simple_format @recipe.body %></td>
                  <%#レシピ詳細を表示する%>
                  <%#simple_formatはbodyの内容の改行を反映させるためのもの%>
                </tr>
              </table>
              <% if @recipe.user.id == current_user.id %>
              <%#もし@recipeに紐付いているユーザーのidと今ログインしている人のidが一致しているのであれば%>
                <%= link_to "編集画面へ", edit_recipe_path(@recipe), class: "button is-success" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            By <%= @recipe.user.username %>
            <%#@recipeを投稿した人を取ってきてその名前を表示する%>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @recipe.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@recipe.user), class: "panel-block" do %>
          <%#(@recipe.user)は@recipeに紐付いているユーザーという意味%>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @recipe.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
    </div>
  </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピグラマー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
      <%#@user変数から一人一人取り出して変数userに格納%>
      <div class="column is-3">
        <div class="card">
          <div class="card-content">
            <div class="card-image">
              <figure class="image">
                <%= link_to user_path(user) do %>
                <%#どのuserのパスに行きたいかなのでuserと書く%>
                  <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                  <%#attachment_image_tagはimageタグと同じ%>
                  <%#userはどこから取ってくるかなので@usersで一つひとつ格納されているのがuserなのでuserを記入%>
                  <%#どのカラムを使用するかなのでprofile_image%>
                  <%#fallback:は何も画像が設定されていなかったら後ろのファイルを実行する%>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user)%></div>
                                    <%#userの中に一人の情報が入っているのでusernameが取ってこれる %>
                </div>
              </div>
              <div class="content">
                投稿数:<%= user.recipes.count %>
                <%#ユーザーに紐付いているレシピをカウントする%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <%#もし詳細画面を表示しているユーザとログインユーザーが一致していたらメールを表示する%>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                    <%#どのユーザーの変種画面にいくかが大事なのでuserを引数として入れておく%>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.recipes.each do |recipe| %>
      <%#recipesとすると一人が投稿したレシピを全て取ってきて全て表示する %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to recipe_path(recipe) do %>
                <%#レシピの詳細画面にいくリンク%>
                  <%= attachment_image_tag recipe, :image, fallback: "no-image.png" %>
                  <%#フォントオーサムを使用したいので doとend でカッコっている%>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to recipe_path(recipe), class: "panel-block" do %>
                  <%#レシピの詳細画面にいくリンク%>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このレシピを見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                  <%#もし投稿した人とログインユーザーが一致したらしたを表示する%>
                    <%= link_to edit_recipe_path(recipe), class: "panel-block" do %>
                    <%#レシピの編集画面にいくリンク%>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to recipe_path(recipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                    <%#レシピを削除するリンク%>
                    <%#data: {confirm: "削除しますか？"}を使うことによって一回で削除できないようになっている。%>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                <%#レシピの更新日が必要だから記載%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>